llm: Qwen/Qwen3-0.6B
feature_extractor_configs:
  - encoder_name: whisper
  - encoder_name: w2vbert
  - encoder_name: sslam
  - encoder_name: muq
from_pretrained: null
llm_embedding_dim: 1024
config:
  use_explicit_audio_tokens: false
  audio_sep_d_embed: ${model.llm_embedding_dim}
  audio_encoder_configs:
    - encoder_name: whisper
    - encoder_name: sslam
    - encoder_name: muq
    - encoder_name: w2vbert
  audio_adapter_configs:
    - encoder_name: whisper
      adapter_name: "downsampler_conformer"
      layer_fusion_config:
        layer_fusion_type: weighted_average
      audio_encoder_layers: [7, 15, 23, 31]
      norm_type: "batch"
      pre_average: true
      downsampler_depth: 1
      use_conformer: false
      encoder_embedding_dim: 1280
      adapter_embedding_dim: 1024
      llm_embedding_dim: ${model.llm_embedding_dim}
    - encoder_name: sslam
      adapter_name: "identity"
      layer_fusion_config:
        layer_fusion_type: weighted_average
      audio_encoder_layers: [3, 7, 11]
      pre_average: true
      adapter_embedding_dim: 1024
      llm_embedding_dim: ${model.llm_embedding_dim}
      use_llm_proj: false
    - encoder_name: muq
      adapter_name: "identity"
      layer_fusion_config:
        layer_fusion_type: weighted_average
      audio_encoder_layers: [4, 8, 12]
      pre_average: true
      adapter_embedding_dim: 1024
      llm_embedding_dim: ${model.llm_embedding_dim}
      use_llm_proj: false
    - encoder_name: w2vbert
      adapter_name: "identity"
      layer_fusion_config:
        layer_fusion_type: weighted_average
      audio_encoder_layers: [6, 10, 15, 20, 24]
      pre_average: true
      adapter_embedding_dim: 1024
      llm_embedding_dim: ${model.llm_embedding_dim}
      use_llm_proj: false
  audio_fusion_config:
    fusion_type: "multiperceiver"
    llm_embedding_dim: ${model.llm_embedding_dim}
    num_latents: [20, 20, 20]
    num_latent_channels: [768, 768, 768]
    num_cross_attention_heads: [4, 4, 4]
    num_cross_attention_layers: [1, 1, 1]
    first_cross_attention_layer_shared: [true, true, true]
    first_self_attention_block_shared: [true, true, true]
    num_self_attention_heads: [4, 4, 4]
    num_self_attention_blocks: [3, 3, 3]
    num_self_attention_layers_per_block: [6, 6, 6]
    main_encoder: "whisper"
    conditional_encoders: ["w2vbert", "muq", "sslam"]
    conditional_embedding_dim: [1024, 1024, 768]
  audio_postprocessing_config:
    postprocessing_type: "identity"
