llm: Qwen/Qwen3-0.6B
feature_extractor_configs:
  - encoder_name: sslam
from_pretrained: null
llm_embedding_dim: 1024
config:
  use_explicit_audio_tokens: false
  audio_sep_d_embed: ${model.llm_embedding_dim}
  audio_encoder_configs:
    - encoder_name: sslam
  audio_adapter_configs:
    - encoder_name: sslam
      adapter_name: "downsampler_conformer"
      layer_fusion_config:
        layer_fusion_type: weighted_average
      audio_encoder_layers: [3, 7, 11]
      norm_type: "layer"
      pre_average: true
      downsampler_depth: 1
      use_conformer: false
      encoder_embedding_dim: 768
      adapter_embedding_dim: 1024
      llm_embedding_dim: ${model.llm_embedding_dim}
  audio_fusion_config:
    fusion_type: "sum"
  audio_postprocessing_config:
    postprocessing_type: "identity"
