groups:
  speech:
    - cameo
    - globe_v3
    - vctk
    - vocalsound
    - ascend
    - disfluencyspeech
    - nisqa
    - mucs
    - mls
    - librispeech
    - asvspoof19
    - asvspoof5
    - noisy_vctk
  complicated_speech:
    - voxceleb1
    - alimeeting
    - amicorpus
    - meld
    - dailytalk
    - librimix
  event:
    - audiocaps
    - clotho
  music:
    - gtzan
    - opensinger
    - singmos
    - mridangam
    - nsynth
    - fma
    - sonicmaster
  environment:
    - esc50
    - fsd50k
    - audioset
  instruction:
    - heysquad
train:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [heysquad_human_filtered_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [heysquad_human_filtered_Qwen3-4B-Thinking-2507_512, "NoContext", 1.0, false]
    - [instructs2s_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [cameo_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [globe_v3_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [vctk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [vocalsound_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [ascend_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [disfluencyspeech_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [nisqa_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [mucs_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [mls_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [librispeech_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [asvspoof19_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [asvspoof5_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [noisy_vctk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [voxceleb1_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [alimeeting_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [amicorpus_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [meld_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [dailytalk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [librimix_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [audiocaps_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [clotho_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [gtzan_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [opensinger_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [singmos_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [mridangam_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [nsynth_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [fma_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [sonicmaster_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [esc50_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [fsd50k_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [audioset_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: train
  limit: null
  return_audio: true
  name: "alldataset"
heysquad_human:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [heysquad_human_filtered_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [heysquad_human_filtered_Qwen3-4B-Thinking-2507_512, "NoContext", 1.0, false]
  split: validation
  limit: null
  return_audio: true
  name: "heysquad_human"
cameo:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [cameo_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "cameo"
globe_v3:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [globe_v3_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "globe_v3"
vctk:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [vctk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "vctk"
vocalsound:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [vocalsound_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "vocalsound"
ascend:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [ascend_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "ascend"
disfluencyspeech:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [disfluencyspeech_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "disfluencyspeech"
nisqa:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [nisqa_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "nisqa"
mucs:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [mucs_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "mucs"
mls:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [mls_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "mls"
librispeech:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [librispeech_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "librispeech"
asvspoof19:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [asvspoof19_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "asvspoof19"
asvspoof5:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [asvspoof5_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "asvspoof5"
noisy_vctk:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [noisy_vctk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "noisy_vctk"
voxceleb1:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [voxceleb1_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "voxceleb1"
alimeeting:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [alimeeting_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "alimeeting"
amicorpus:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [amicorpus_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "amicorpus"
meld:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [meld_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "meld"
dailytalk:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [dailytalk_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "dailytalk"
librimix:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [librimix_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "librimix"
audiocaps:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [audiocaps_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "audiocaps"
clotho:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [clotho_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "clotho"
gtzan:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [gtzan_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "gtzan"
opensinger:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [opensinger_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "opensinger"
singmos:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [singmos_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "singmos"
mridangam:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [mridangam_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "mridangam"
nsynth:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [nsynth_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "nsynth"
fma:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [fma_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "fma"
sonicmaster:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [sonicmaster_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "sonicmaster"
esc50:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [esc50_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "esc50"
fsd50k:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [fsd50k_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "fsd50k"
audioset:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [audioset_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "audioset"
