groups:
  # speech:
  #   - cameo
  #   - globe_v3
  #   - vctk
  #   - vocalsound
  #   - ascend
  #   - disfluencyspeech
  #   - nisqa
  #   - mucs
  #   - mls
  #   - librispeech
  #   - asvspoof19
  #   - asvspoof5
  #   - noisy_vctk
  # complicated_speech:
  #   - voxceleb1
  #   - alimeeting
  #   - amicorpus
  #   - meld
  #   - dailytalk
  #   - librimix
  # event:
  #   - audiocaps
  #   - clotho
  music:
    # - gtzan
    # - opensinger
    # - singmos
    # - mridangam
    - nsynth
    # - fma
    - sonicmaster
  # environment:
  #   - esc50
  #   - fsd50k
  #   - audioset
  # instruction:
  #   - heysquad
train:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [nsynth_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
    - [sonicmaster_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: train
  limit: null
  return_audio: true
  name: "music"
nsynth:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [nsynth_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "nsynth"
sonicmaster:
  _target_: src.dataset.HFDataset
  dataset_names:
    - [sonicmaster_rephrased_1536_Qwen3-4B-Thinking-2507_512, "WithContext", 1.0, false]
  split: validation # created via train_test_split
  limit: null
  return_audio: true
  name: "sonicmaster"
